hackapp/urls.py
from django.contrib.auth import views
from django.urls import path
from django.contrib.auth import views as user_views
from . import views


urlpatterns = [
    path('signup/', views.signUp, name='signup'),
    path('login/', user_views.LoginView.as_view(template_name="hackapp/login.html"), name="login"),
    path('home/', views.view_post, name="home"),
    path('newest/', views.newest, name='newest'),
    path('newestcomments/', views.newest_comments, name='newestcomments'),
    path('welcome/', views.welcome, name='welcome'),
    path('post/create_post/', views.create_post, name='create_post'), 
    path('post/create_post_action/', views.create_post_action, name='create_post_action'),
    path('post/<post_id>/', views.view_one_post, name='view_post'),
    path('post/<post_id>/delete_post/', views.delete_post, name='delete_post'),
    path('post/<post_id>/delete_post_action/', views.delete_post_action, name='delete_post_action'),
    path('logout/', user_views.LogoutView.as_view(template_name="hackapp/logout.html"), name="logout"),
    path('accounts/profile/', views.profile, name='profile'),
    path('post/<post_id>/create_comment', views.create_comment, name='create_comment'),
    path('', views.redirect_home, name='redirect_home')
    #path('user/view/<user_id>', views.view_user, name='view'),
    #path('user/delete_user', views.delete_user, name='delete_user'),
    #path('post/<post_id>/edit', views.edit_post, name='edit_post'),
    # path('post/<post_id>', views.view_post, name='view_post'),
    # path('post/<post_id>/edit', views.edit_post, name='edit_post'),
]

hackernews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('hackapp.urls')),
]

hackapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

"""
class Users(models.Model):
    user_name = models.CharField(max_length=15)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    vote_count = models.IntegerField(default=0)
"""

class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    url = models.CharField(max_length=50, default="null")
    body = models.TextField(max_length=5000)
    vote_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

class Comments(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=5000)
    vote_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Posts', on_delete=models.DO_NOTHING)

hackapp/views.py
from django.shortcuts import render, redirect
from .models import Posts, Comments
from django.contrib.auth.models import User, Permission
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from . form import UserCreationFormSpec
import requests
# Create your views here.

#Lorenzo's 

def welcome(request):
    return render(request, 'welcome.html')

def redirect_home(request):
    return redirect("home")
    
def view_post(request):
    acct = request.user
    all_posts = Posts.objects.all()
    post_counter = 1 
    context = {"account": acct, "all_posts": all_posts, "post_counter": post_counter}
    return render(request, 'home.html', context)

def view_one_post(request, post_id):
    post = Posts.objects.get(pk=post_id)
    comments = Comments.objects.filter(post=post)
    context = {"post": post, "comments": comments}
    return render(request, 'post.html', context)

def newest(request):
    acct = request.user
    all_posts = Posts.objects.all().order_by('-created_at')
    context = {"account": acct, "all_posts": all_posts}
    return render(request, 'home.html', context)

def newest_comments(request):
    acct = request.user 
    all_comments = Comments.objects.all().order_by('-created_at')
    context = {"account": acct, "comments": all_comments}
    return render(request, 'comments.html', context)
    
def create_post(request):
    return render(request, "create_posts.html")

def create_post_action(request):
    if request.user.is_authenticated:
        current_user = request.user
        acct = User.objects.get(id=current_user.id)
        #try: 
        if request.method == "POST":
            postpost = request.POST.dict()
            title = postpost["title"]
            url =  postpost["url"]
            text = postpost["text"]
            post = Posts.objects.create(author=acct, title=title, url=url, body=text)
            post.save()
            return redirect("home")
        #except:
            #return redirect("create_post")

def delete_post(request, post_id):
    post = Posts.objects.get(pk=post_id)
    context = {"post": post}
    return render(request, "delete_posts.html", context)

def delete_post_action(request, post_id):
    post = Posts.objects.get(pk=post_id)
    post.delete()
    return redirect("home")

def create_comment(request, post_id):
    if request.user.is_authenticated:
        current_user = request.user
        acct = User.objects.get(id=current_user.id)
        post = Posts.objects.get(pk=post_id)
        if request.method == "POST":
            comment_query = request.POST.dict()
            comment_text = comment_query["text"]
            comment = Comments.objects.create(author=acct, post=post, body=comment_text)
            comment.save()
            return redirect('/post/' + str(post.id) + "/")
        else:
            return redirect("home")
    else:
        return redirect("login")
    

def signUp(request):
    if request.method == "POST":
        form = UserCreationFormSpec(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            user = User.objects.get(username=username)
            add_user_perm(user)
            print(user)
            return redirect('login')
    else:
        form = UserCreationFormSpec()
    return render(request, "hackapp/signup.html", {"form": form})

@login_required
def profile(request):
    return render(request, "hackapp/inform.html")

def add_user_perm(user):
    permission = Permission.objects.get(name='Can add posts')
    user.user_permissions.add(permission)
    permission = Permission.objects.get(name='Can change posts')
    user.user_permissions.add(permission)
    permission = Permission.objects.get(name='Can delete posts')
    user.user_permissions.add(permission)
    permission = Permission.objects.get(name='Can view posts')
    user.user_permissions.add(permission)
    permission = Permission.objects.get(name='Can add comments')
    user.user_permissions.add(permission)
    permission = Permission.objects.get(name='Can change comments')
    user.user_permissions.add(permission)
    permission = Permission.objects.get(name='Can delete comments')
    user.user_permissions.add(permission)
    permission = Permission.objects.get(name='Can view comments')
    user.user_permissions.add(permission)
    
    
"""


def delete_post(request, post_id):
    #acct_id = request.sessions.get("acct_id")
    acct = User.objects.get(pk=1)
    post = Posts.objects.get(pk=post_id)
    context = {"acct": acct, "post": post}
    return render(request, "delete_posts.html", context)

def delete_post_action(request, post_id):
    #acct_id = request.sessions.get("acct_id")
    #acct = Users.objects.get(pk=1)
    post = Posts.objects.get(pk=post_id)
    post.delete()
    return redirect("home")







# =======
# from django.http import HttpResponse, JsonResponse
# from .models import *
# from django.contrib.auth.models import *
# >>>>>>> 2ee1f479b9a7eed87b45fc7f2594bb678c64e746
"""
# def new_user(req):
#     """displays form for creating new user"""
#     return render(req, 'hackapp/new.html')
    
# def create_user(req):
#     """gets user info in POST"""
#     if req.method == 'POST':
#         new_user = User(username = req.POST["username"], email = req.POST["email"])
#         new_user.set_password(req.POST["password"])
#         new_users = Users.objects.create(user_name=new_user.username, email=new_user.email)
#         new_user.save()
#         new_users.save()
#         return redirect('../..')
#     return redirect('./new')

# def view_user(req, username):
#     """shows a user profile"""
#     if not req.user.is_authenticated:
#         return redirect('login')
#     username = req.user.username
#     context = {"username": username}
#     if "error" in req.GET:
#         context["error"] = req.GET["error"]
#     return render(req, 'user/profile.html', context)

# def delete_user(req, username):
#     """deletes a user"""
#     if req.user.is_authenticated:
#         try:
#             u = User.objects.get(username=username)
#             u.delete()
#             messages.success(request, "user deleted")
#             return redirect('login')
#         except User.DoesNotExist:
#             messages.error(request, "user does not exist")
#             return redirect('delete_user')
#         except Exception:
#             return redirect('delete_user')
#     return redirect('delete_user')

hackapp/templates/comments.html
{% extends 'layout.html' %}

{% block content %}
      {% for comment in comments %}
          <table border="0" class="comment-tree">
            <tbody><tr class="athing comtr " id="21218510"><td>
              <table border="0">  
                <tbody><tr>    
                  <td class="ind"><img src="" height="1" width="0"></td>
                    <td valign="top" class="votelinks">
                      <center>  
                        <a id="up_21218510" onclick="return vote(event, this, &quot;up&quot;)" href="vote?id=21218510&amp;how=up&amp;auth=caf5296fe44cf32101ac828ae4b6001ba7a0098d&amp;goto=item%3Fid%3D21218482#21218510">
                        <div class="votearrow" title="upvote"></div></a>
                      </center>
                    </td>
                    <td class="default">
                      <div style="margin-top:2px; margin-bottom:-10px;">
                        <span class="comhead">
                          <a href="" class="hnuser">{{comment.author}}</a> 
                          <span class="age"><a href="item?id=21218510">{{comment.created_at}}</a></span> 
                          <span id="unv_21218510"></span>
                          <span class="par"></span> 
                          <a href="/post/{{comment.post.id}}/" class="hnuser">{{comment.post.title}}</a> 
                          <span class="storyon"></span>
                        </span>
                      </div><br>
                      <div class="comment">
                          <span class="commtext c00">{{comment.body}}</span>
                      <div class="reply">        
                        <p>
                          <font size="1">
                            <u><a href="reply?id=21218510&amp;goto=item%3Fid%3D21218482%2321218510">reply</a></u>
                          </font>
                        </p>
                      </div>
                    </div>
                    </td>
                  </tr>
                </tbody>
              </table></td></tr>
            </tbody>
          </table>
          <br><br>
        {% endfor %}  
  </td></tr> 

  {% endblock %}

hackapp/templates/create_posts.html
<html op="submit">
    <head>
    <meta name="referrer" content="origin">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="http://cdn.onlinewebfonts.com/svg/img_456930.png">
    <title>Submit | Hacker News</title>
    </head>
    
    <body>
        <center>
        <table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
            <tbody>
                <tr>
                    <td bgcolor="#ff6600">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
                            <tbody>
                                <tr>
                                    <td style="width:18px;padding-right:4px">
                                        <a href="/home"><img src="https://image.flaticon.com/icons/png/128/260/260235.png" width="18" height="18" style="border:1px #ffffff solid;"></a>
                                    </td>
                                    <td style="line-height:12pt; height:10px;">
                                    <span class="pagetop"><b>Submit</b></span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr style="height:10px"></tr>
                <tr>
                    <td>
                        <form method="post" action="/post/create_post_action/">
                         {% csrf_token %}
                            <script type="text/javascript">function tlen(el) { var n = el.value.length - 80; el.nextSibling.innerText = n > 0 ? n + ' too long' : ''; }</script>
                            <table border="0">
                                <tbody>
                                    <tr>
                                        <td>title</td>
                                            <td><input type="text" name="title" value="" size="50" oninput="tlen(this)" onfocus="tlen(this)">
                                            <span style="margin-left:10px"></span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>url</td>
                                        <td>
                                            <input type="text" name="url" value="" size="50">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td><b>or</b></td>
                                    </tr>
                                    <tr>
                                        <td>text</td>
                                        <td>
                                            <textarea name="text" rows="4" cols="49"></textarea>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>
                                            <input type="submit" value="submit">
                                        </td>
                                    </tr>
                                    <tr style="height:20px"></tr>
                                        <tr>
                                            <td></td>
                                            <td>Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.<br>
                                            <br>You can also submit via <a href="bookmarklet.html" rel="nofollow"><u>bookmarklet</u></a>.
                                            </td>
                                        </tr>
                                </tbody>
                            </table>
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
        </center>
    </body>
</html>                   

hackapp/templates/home.html
{% extends 'layout.html' %}

         <!--POSTS TABLE-->
        {% block content %}
        <table border="0" cellpadding="0" cellspacing="0" class="itemlist">
           
            {% for post in all_posts %}
                
                <tbody>
                    <tr class="athing" id="21202905">
                    <td align="right" valign="top" class="title">
                        <span class="rank">{{ forloop.counter }}.</span>
                    </td>      
                    <td valign="top" class="votelinks">
                        <center><a id="up_21202905" onclick="return vote(event, this, &quot;up&quot;)" href="vote?id=21202905&amp;how=up&amp;auth=1f73fe414f1e4134aa334c4b5c3d21a6fe262f02&amp;goto=news">
                            <div class="votearrow" title="upvote"></div></a>
                        </center>
                    </td>

                    <td class="title"><a href={{post.url}} class="storylink">{{post.title}}</a><span class="sitebit comhead"> (<a href={{post.url}}><span class="sitestr">{{post.url}}</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
                        <span class="score" id="score_21202905">{{post.vote_count}} points</span> 
                        by <a href="" class="hnuser">{{post.author}}</a> 
                        <span class="age"><a href="item?id=21202905">{{post.created_at}}</a></span> 
                        <span id="unv_21202905"></span> | 
                        <a href="" onclick="return hidestory(event, this, 21202905)">hide</a> | 
                        <a href='/post/{{post.id}}'>{{ post.comments_set.count }} comments</a>
                        {% if account == post.author %}
                        | <a href="edit?id=21210749">edit</a> 
                        | <a href="/post/{{post.id}}/delete_post">delete</a>
                        {% endif %}
                        {% if account != post.author %}
                        | <a href="/post/{{post.id}}/">discuss</a> 
                        {% endif %}
                        </td></tr> 

            {% endfor %}
                    <tr class="spacer" style="height:5px"></tr>
                
                    <tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td><td class="title"><a href="news?p=2" class="morelink" rel="next">More</a></td></tr>
                </tbody>
            </table>
</td></tr>

  {% endblock %}

hackapp/templates/post.html
{% extends 'layout.html' %}

{% block content %}
<tr><td>
  <table class="fatitem" border="0">
        <tbody>
          <tr class="athing" id="21218482">
      <td align="right" valign="top" class="title"><span class="rank"></span></td>      
      <td valign="top" class="votelinks">
      <center><a id="up_21218482" onclick="return vote(event, this, &quot;up&quot;)" href="vote?id=21218482&amp;how=up&amp;auth=cad8ed528e88a7e670d6e0c5b2cc4d1f50c62dc7&amp;goto=item%3Fid%3D21218482">
        <div class="votearrow" title="upvote"></div></a></center></td>
        <td class="title"><a href={{post.url}} class="storylink" rel="nofollow">{{post.title}}</a><span class="sitebit comhead"> (<a href={{post.url}}><span class="sitestr">{{post.url}}</span></a>)</span></td></tr>
        <tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_21218482">0 point</span> by <a href="user/{{acct.username}}" class="hnuser">{{post.author}}</a> <span class="age"><a href="item?id=21218482">{{post.created_at}}</a></span> <span id="unv_21218482"></span> | 
        <a href="hide?id=21218482&amp;auth=cad8ed528e88a7e670d6e0c5b2cc4d1f50c62dc7&amp;goto=item%3Fid%3D21218482">hide</a> | 
        <a href="https://hn.algolia.com/?query=Native%20HTML%20quadplay%20fantasy%20console&amp;sort=byDate&amp;dateRange=all&amp;type=story&amp;storyText=false&amp;prefix&amp;page=0" class="hnpast">past</a> | 
        <a href="https://www.google.com/search?q=Native%20HTML%20quadplay%20fantasy%20console">web</a> | 
        <a href="fave?id=21218482&amp;auth=cad8ed528e88a7e670d6e0c5b2cc4d1f50c62dc7">favorite</a> | 
        <a href="item?id=21218482">{{ post.comments_set.count }} comment</a>              </td></tr>
            <tr style="height:10px"></tr><tr><td colspan="2"></td><td>

          <form method="post" action="/post/{{post.id}}/create_comment">
          {% csrf_token %}
            <input type="hidden" name="post_author" value="{{post.author}}">
              <input type="hidden" name="post_id" value="{{post.id}}">
                <input type="hidden" name="hmac" value="26d6edbd06bb2bab85daf4eecc1dd1c94c05b400">
                <textarea name="text" rows="6" cols="60"></textarea>
                  <br><br><span class="subtext">If you haven't already, would you mind reading
                  about HN's <a href="/welcome"><u>approach to comments</u></a>
                  and <a href="/welcome"><u>site guidelines</u></a>?
                </span>
                      <br><br><input type="submit" value="add comment">
          </form>

      </td></tr>
  </tbody></table><br><br>

  {% if post.comments_set.count > 0 %}
      {% for comment in comments %}
          <table border="0" class="comment-tree">
            <tbody><tr class="athing comtr " id="21218510"><td>
              <table border="0">  
                <tbody><tr>    
                  <td class="ind"><img src="" height="1" width="0"></td>
                    <td valign="top" class="votelinks">
                      <center>  
                        <a id="up_21218510" onclick="return vote(event, this, &quot;up&quot;)" href="vote?id=21218510&amp;how=up&amp;auth=caf5296fe44cf32101ac828ae4b6001ba7a0098d&amp;goto=item%3Fid%3D21218482#21218510">
                        <div class="votearrow" title="upvote"></div></a>
                      </center>
                    </td>
                    <td class="default">
                      <div style="margin-top:2px; margin-bottom:-10px;">
                        <span class="comhead">
                          <a href="user?id=Tepix" class="hnuser">{{comment.author}}</a> 
                          <span class="age"><a href="item?id=21218510">{{comment.created_at}}</a></span> 
                          <span id="unv_21218510"></span>
                          <span class="par"></span> 
                          <a class="togg" n="1" href="javascript:void(0)" onclick="return toggle(event, 21218510)">[-]</a>          
                          <span class="storyon"></span>
                        </span>
                      </div><br>
                      <div class="comment">
                          <span class="commtext c00">{{comment.body}}</span>
                      <div class="reply">        
                        <p>
                          <font size="1">
                            <u><a href="reply?id=21218510&amp;goto=item%3Fid%3D21218482%2321218510">reply</a></u>
                          </font>
                        </p>
                      </div>
                    </div>
                    </td>
                  </tr>
                </tbody>
              </table></td></tr>
            </tbody>
          </table>
          <br><br>
        {% endfor %}
  {% endif %}
  
  </td></tr> 

  {% endblock %}

hackapp/templates/welcome.html
<body bgcolor="#ffffff">
<center>
<br><br>
<table width="500" cellpadding="0">
<tbody><tr><td bgcolor="#fafaf0">
<a href="/home"><img src="http://www.clker.com/cliparts/7/y/k/r/I/R/news-paper-with-lines-hi.png" border="0" width="500"></a>
<br><br>
<b>Welcome to Hacker News</b>
<br><br>
<p>
<a href="/home">Hacker News</a> is a bit
different from other community sites, and we'd appreciate it if
you'd take a minute to read the following as well as the <a href="newsguidelines.html">official guidelines</a>.
</p><p>
HN is an experiment.  As a rule, a community site that becomes
popular will decline in quality.  Our hypothesis is that this is not
inevitable—that by making a conscious effort to resist
decline, we can keep it from happening.
</p><p>
Essentially there are two rules here: don't post or upvote crap
links, and don't be rude or dumb in comment threads.
</p><p>
A crap link is one that's only superficially
interesting. Stories on HN don't have to be
about hacking, because good hackers aren't only interested in hacking,
but they do have to be deeply interesting.
</p><p>
What does "deeply interesting" mean?  It means stuff that teaches you
about the world.  A story about a robbery, for example, would
probably not be deeply interesting.  But if this robbery was a sign
of some bigger, underlying trend, perhaps it could be.
</p><p>
The worst thing to post or upvote is something that's
intensely but shallowly interesting: gossip about famous people,
funny or cute pictures or videos, partisan political articles, etc.
If you let <ax href="http://en.wikipedia.org/wiki/Nile_perch">that
sort of thing onto a news site, it will push
aside the deeply interesting stuff, which tends to be quieter.
</ax></p><p>
The most important principle on HN, though, is to make thoughtful
comments.  Thoughtful in both senses: civil and substantial.
</p><p>
The test for substance is a lot like it is for links. Does your
comment teach us anything?  There are two ways to do that: by
pointing out some consideration that hadn't previously been mentioned,
and by giving more information about the topic, perhaps from personal
experience.  Whereas comments like "LOL!" or worse still, "That's
retarded!" teach us nothing.
</p><p>
Empty comments can be ok if they're positive.  There's nothing wrong
with submitting a comment saying just "Thanks."  What we especially
discourage are comments that are empty and negative—comments
that are mere name-calling.
</p><p>
Which brings us to the most important principle
on HN: civility.  Since long before the web, the anonymity of online
conversation has lured people into being much ruder than they'd
be in person.  So the principle here is: don't say anything
you wouldn't say face to face.  This doesn't mean you can't disagree.
But disagree without calling names.
If you're right, your argument will be more convincing without them.
<br><br><br>
<table width="100%" bgcolor="#ff6600" cellpadding="0"><tbody><tr><td></td></tr></tbody></table>
</p><p align="center">
<span class="foot">


<br><br>
</span>
</p></td></tr></tbody></table>
</center>

</body>

<style>
body { font-family:Verdana; font-size:8.5pt; }
td { font-family:Verdana; font-size:8.5pt; line-height:138%; }
blockquote {line-height:122%; }
p { margin-bottom:15px; }

a:link    { color:#222222; }
a:visited { color:#444444; }
b { color:#333333; }

.foot { font-size:7.5pt; }
.foot a:link, .foot a:visited { text-decoration:none; }
.foot a:hover { text-decoration:underline; }

.apply a:link { color:#0000ff; font-size:9pt; }
.apply a:visited { color:#0000ff; font-size:9pt; }

.title { font-size:10pt; }
.title b { color:#000000; }

.big { margin-top:3ex; }
.small { margin-top:-1.6ex; }

</style>